version: '3.8'

services:
  todo-app:
    dns:
      - 8.8.8.8
    image: margam59/todo-app:latest
    container_name: todo-app-service
    ports:
      - "4000:4000"
    environment:
      - mongoDbUrl=${mongoDbUrl}
      - PORT=4000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://127.0.0.1:4000/health', res => process.exit(res.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - todo-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - todo-network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - todo-network
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - todo-network
    restart: unless-stopped

  watchtower:
    dns:
      - 8.8.8.8
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json:ro
    environment:

      - WATCHTOWER_USERNAME=${DOCKER_HUB_USERNAME}

      - WATCHTOWER_PASSWORD=${DOCKER_HUB_PASSWORD}
    command: todo-app-service grafana prometheus cadvisor --interval 30 --cleanup --include-restarting
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  grafana-storage:

