apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      imagePullSecrets:
      - name: dockerhub-secret  # Reference to the secret
      containers:
      - name: todo-app
        image: margam59/todo-app:latest
        ports:
        - containerPort: 4000
        env:
        - name: MONGO_USER
          value: mariemgamal
        - name: MONGO_PASS
          value: mg592001
        - name: mongoDbUrl
          value: mongodb+srv://mariemgamal:mg592001@cluster0.6xe3vyw.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

